#pragma once


namespace	DEFAULTMESSAGEBOX_ID
{
#define IDC_BUTTON_TEMPLATE 1004
#define IDC_DEFBTN_TEMPLATE 1006
#define IDC_MSGTEXT_TEMPLATE 1003
#define IDC_PANEL_CLIENT_BKG 1010
#define IDC_PICTURE_ICON 1002
#define IDC_PICTURE_TITLE_ICON 1008
#define IDC_STATIC_CAPTION 1009
}
